version: "3"
services:
  airflow:
    image: apache/airflow:2.9.2
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW_UID=50000
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - _PIP_ADDITIONAL_REQUIREMENTS=-r /opt/airflow/requirements.txt
    command: standalone
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8080:8080"